package spec

import (
	"fmt"
	"path/filepath"
	"strings"
)

const (
	skillBundleDir  = "skills/fakturownia"
	skillDocsIndex  = "docs/skills.md"
	generatedByLine = "> Auto-generated by `go run ./cmd/gen-skills`. Do not edit manually."
)

type SkillCommandRef struct {
	Noun string `json:"noun"`
	Verb string `json:"verb"`
}

type SkillAreaSpec struct {
	Key           string            `json:"key"`
	Name          string            `json:"name"`
	Title         string            `json:"title"`
	Description   string            `json:"description"`
	Category      string            `json:"category"`
	Prerequisite  string            `json:"prerequisite,omitempty"`
	RelatedSkills []string          `json:"related_skills,omitempty"`
	CommandRefs   []SkillCommandRef `json:"command_refs,omitempty"`
	ExampleRefs   []SkillCommandRef `json:"example_refs,omitempty"`
	CLIHelp       string            `json:"cli_help"`
	RequiresBins  []string          `json:"requires_bins,omitempty"`
	DiscoveryHint string            `json:"discovery_hint,omitempty"`
	WhenToUse     []string          `json:"when_to_use,omitempty"`
}

type SkillBundleSpec struct {
	Name          string          `json:"name"`
	Title         string          `json:"title"`
	Description   string          `json:"description"`
	CLIHelp       string          `json:"cli_help"`
	RequiresBins  []string        `json:"requires_bins,omitempty"`
	DiscoveryHint string          `json:"discovery_hint,omitempty"`
	Areas         []SkillAreaSpec `json:"areas"`
}

func SkillBundle() SkillBundleSpec {
	return SkillBundleSpec{
		Name:        "fakturownia",
		Title:       "fakturownia",
		Description: "Fakturownia CLI bundle: shared guidance, auth, clients, invoices, self-update, schema discovery, and diagnostics for the `fakturownia` command. Use when an agent needs to work with Fakturownia through this CLI.",
		CLIHelp:     "fakturownia --help",
		RequiresBins: []string{
			"fakturownia",
		},
		DiscoveryHint: "Open the bundle-local skills index first, then read the shared skill, then the area skill that matches the task.",
		Areas: []SkillAreaSpec{
			{
				Key:         "shared",
				Name:        "fakturownia-shared",
				Title:       "Shared",
				Description: "Fakturownia CLI shared patterns: authentication prerequisites, global flags, output modes, `--fields` vs `--columns`, `--raw`, schema discovery, and binary maintenance. Use before any area-specific fakturownia task.",
				Category:    "core",
				CommandRefs: []SkillCommandRef{
					{Noun: "self", Verb: "update"},
				},
				ExampleRefs: []SkillCommandRef{
					{Noun: "auth", Verb: "login"},
					{Noun: "schema", Verb: "list"},
					{Noun: "self", Verb: "update"},
					{Noun: "client", Verb: "list"},
					{Noun: "invoice", Verb: "list"},
				},
				CLIHelp: "fakturownia --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Start here for global behavior, then use `fakturownia schema list --json` to discover supported command groups.",
				WhenToUse: []string{
					"The task is generally about the `fakturownia` CLI rather than one specific noun.",
					"You need auth setup, global flags, output behavior, or command discovery before calling API-area commands.",
					"You need to update the installed fakturownia binary from GitHub Releases.",
				},
			},
			{
				Key:          "auth",
				Name:         "fakturownia-auth",
				Title:        "Auth",
				Description:  "Fakturownia CLI auth: persist, inspect, and remove profiles and API tokens with `fakturownia auth ...`.",
				Category:     "core",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "auth", Verb: "login"},
					{Noun: "auth", Verb: "status"},
					{Noun: "auth", Verb: "logout"},
				},
				CLIHelp: "fakturownia auth --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `auth login` before API calls, or `auth status --json` to inspect the resolved profile and token source.",
				WhenToUse: []string{
					"You need to save a profile, verify which profile is active, or clean up a persisted token.",
					"You need to explain or troubleshoot how env vars, profiles, and keychain-backed credentials resolve.",
				},
			},
			{
				Key:          "clients",
				Name:         "fakturownia-clients",
				Title:        "Clients",
				Description:  "Fakturownia CLI clients: list, fetch, create, update, and delete clients, and inspect README-backed client fields and request schemas.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "client", Verb: "list"},
					{Noun: "client", Verb: "get"},
					{Noun: "client", Verb: "create"},
					{Noun: "client", Verb: "update"},
					{Noun: "client", Verb: "delete"},
				},
				CLIHelp: "fakturownia client --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema client list --json` for output fields and `fakturownia schema client create --json` or `client update --json` for request-body discovery before building selectors or payloads.",
				WhenToUse: []string{
					"The task is about reading or mutating clients, including lookup by external ID.",
					"You need to build a client payload from README-backed field definitions and inspect `request_body_schema` before create or update calls.",
				},
			},
			{
				Key:          "invoices",
				Name:         "fakturownia-invoices",
				Title:        "Invoices",
				Description:  "Fakturownia CLI invoices: list invoices, fetch a single invoice, download invoice PDFs, and discover invoice fields through schema output.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "invoice", Verb: "list"},
					{Noun: "invoice", Verb: "get"},
					{Noun: "invoice", Verb: "download"},
				},
				CLIHelp: "fakturownia invoice --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema invoice list --json` or `fakturownia schema invoice get --json` before building `--fields` selectors or nested invoice projections.",
				WhenToUse: []string{
					"The task is about reading invoices, narrowing invoice fields, or downloading invoice PDFs.",
					"You need to discover invoice output fields such as `number`, `status`, or nested paths like `positions[].name`.",
				},
			},
			{
				Key:          "schema",
				Name:         "fakturownia-schema",
				Title:        "Schema",
				Description:  "Fakturownia CLI schema discovery: inspect supported commands, flags, examples, exit codes, and output schemas with `fakturownia schema ...`.",
				Category:     "core",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"invoices",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "schema", Verb: "list"},
					{Noun: "schema", Verb: "<noun> <verb>"},
				},
				CLIHelp: "fakturownia schema --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use schema output to inspect a command before calling it; for invoices, read `output.known_fields` and `path_syntax`.",
				WhenToUse: []string{
					"You need machine-readable command discovery instead of scraping `--help` text.",
					"You need to inspect flags, env vars, examples, exit codes, or output catalogs before executing a command.",
				},
			},
			{
				Key:          "doctor",
				Name:         "fakturownia-doctor",
				Title:        "Doctor",
				Description:  "Fakturownia CLI diagnostics: validate config resolution, keychain access, reachability, authenticated API access, and release integrity with `fakturownia doctor run`.",
				Category:     "core",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"auth",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "doctor", Verb: "run"},
				},
				CLIHelp: "fakturownia doctor --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use doctor when auth or API behavior is unclear and you need deterministic remediation checks instead of guessing.",
				WhenToUse: []string{
					"You need a deterministic health check for config, auth, network, or release integrity.",
					"You are debugging a failed API call and want the CLI to verify the local environment first.",
				},
			},
		},
	}
}

func skillAreaByKey(bundle SkillBundleSpec, key string) (SkillAreaSpec, bool) {
	for _, area := range bundle.Areas {
		if area.Key == key {
			return area, true
		}
	}
	return SkillAreaSpec{}, false
}

func commandSpecForSkillRef(ref SkillCommandRef) (CommandSpec, error) {
	spec, ok := FindCommand(ref.Noun, ref.Verb)
	if !ok {
		return CommandSpec{}, fmt.Errorf("unknown skill command reference %s %s", ref.Noun, ref.Verb)
	}
	return spec, nil
}

func skillCommandAssignments(bundle SkillBundleSpec) (map[SkillCommandRef]string, error) {
	assignments := make(map[SkillCommandRef]string)
	for _, area := range bundle.Areas {
		for _, ref := range area.CommandRefs {
			if _, err := commandSpecForSkillRef(ref); err != nil {
				return nil, err
			}
			if owner, ok := assignments[ref]; ok {
				return nil, fmt.Errorf("skill command reference %s %s assigned to both %s and %s", ref.Noun, ref.Verb, owner, area.Key)
			}
			assignments[ref] = area.Key
		}
	}
	return assignments, nil
}

func commandsForSkillArea(area SkillAreaSpec) ([]CommandSpec, error) {
	specs := make([]CommandSpec, 0, len(area.CommandRefs))
	for _, ref := range area.CommandRefs {
		spec, err := commandSpecForSkillRef(ref)
		if err != nil {
			return nil, err
		}
		specs = append(specs, spec)
	}
	return specs, nil
}

func exampleCommandsForSkillArea(area SkillAreaSpec) ([]CommandSpec, error) {
	refs := area.CommandRefs
	if len(area.ExampleRefs) > 0 {
		refs = area.ExampleRefs
	}
	seen := make(map[SkillCommandRef]struct{}, len(refs))
	specs := make([]CommandSpec, 0, len(refs))
	for _, ref := range refs {
		if _, ok := seen[ref]; ok {
			continue
		}
		seen[ref] = struct{}{}
		spec, err := commandSpecForSkillRef(ref)
		if err != nil {
			return nil, err
		}
		specs = append(specs, spec)
	}
	return specs, nil
}

func envVarsForCommands(specs []CommandSpec) []EnvVarSpec {
	seen := map[string]struct{}{}
	out := make([]EnvVarSpec, 0)
	for _, spec := range specs {
		for _, env := range spec.EnvVars {
			if _, ok := seen[env.Name]; ok {
				continue
			}
			seen[env.Name] = struct{}{}
			out = append(out, env)
		}
	}
	return out
}

func flagsForCommands(specs []CommandSpec) []FlagSpec {
	seen := map[string]struct{}{}
	out := make([]FlagSpec, 0)
	for _, spec := range specs {
		for _, flag := range spec.LocalFlags {
			if _, ok := seen[flag.Name]; ok {
				continue
			}
			seen[flag.Name] = struct{}{}
			out = append(out, flag)
		}
	}
	return out
}

func examplesForCommands(specs []CommandSpec) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0)
	for _, spec := range specs {
		for _, example := range spec.Examples {
			if _, ok := seen[example]; ok {
				continue
			}
			seen[example] = struct{}{}
			out = append(out, example)
		}
	}
	return out
}

func bundleRootSkillPath() string {
	return filepath.ToSlash(filepath.Join("skills", "fakturownia", "SKILL.md"))
}

func bundleIndexPath() string {
	return filepath.ToSlash(filepath.Join("skills", "fakturownia", "references", "skills-index.md"))
}

func skillAreaPath(area SkillAreaSpec) string {
	return filepath.ToSlash(filepath.Join("skills", "fakturownia", "subskills", area.Key, "SKILL.md"))
}

func docsSkillsPath() string {
	return skillDocsIndex
}

func sharedSkillArea(bundle SkillBundleSpec) SkillAreaSpec {
	area, ok := skillAreaByKey(bundle, "shared")
	if !ok {
		panic("missing shared skill area")
	}
	return area
}

func skillAreaCommandTitle(spec CommandSpec) string {
	if spec.Verb == "<noun> <verb>" {
		return "fakturownia " + spec.Noun + " <noun> <verb>"
	}
	return "fakturownia " + spec.Noun + " " + spec.Verb
}

func relatedAreas(bundle SkillBundleSpec, area SkillAreaSpec) []SkillAreaSpec {
	out := make([]SkillAreaSpec, 0, len(area.RelatedSkills))
	for _, key := range area.RelatedSkills {
		resolved, ok := skillAreaByKey(bundle, key)
		if ok {
			out = append(out, resolved)
		}
	}
	return out
}

func skillsByCategory(bundle SkillBundleSpec, category string) []SkillAreaSpec {
	out := make([]SkillAreaSpec, 0)
	for _, area := range bundle.Areas {
		if area.Category == category {
			out = append(out, area)
		}
	}
	return out
}

func validateSkillBundle(bundle SkillBundleSpec) error {
	if strings.TrimSpace(bundle.Name) == "" {
		return fmt.Errorf("skill bundle name is required")
	}
	if _, err := skillCommandAssignments(bundle); err != nil {
		return err
	}
	expected := make([]SkillCommandRef, 0, len(Registry()))
	for _, command := range Registry() {
		expected = append(expected, SkillCommandRef{Noun: command.Noun, Verb: command.Verb})
	}
	assignments, err := skillCommandAssignments(bundle)
	if err != nil {
		return err
	}
	for _, ref := range expected {
		if _, ok := assignments[ref]; !ok {
			return fmt.Errorf("command %s %s is not assigned to any skill area", ref.Noun, ref.Verb)
		}
	}
	for _, area := range bundle.Areas {
		if strings.TrimSpace(area.Name) == "" {
			return fmt.Errorf("skill area %s is missing a name", area.Key)
		}
		if strings.TrimSpace(area.Description) == "" {
			return fmt.Errorf("skill area %s is missing a description", area.Key)
		}
		if area.Prerequisite != "" {
			if _, ok := skillAreaByKey(bundle, area.Prerequisite); !ok {
				return fmt.Errorf("skill area %s has unknown prerequisite %s", area.Key, area.Prerequisite)
			}
		}
		for _, related := range area.RelatedSkills {
			if _, ok := skillAreaByKey(bundle, related); !ok {
				return fmt.Errorf("skill area %s has unknown related skill %s", area.Key, related)
			}
		}
	}
	return nil
}
