package spec

import (
	"fmt"
	"path/filepath"
	"strings"
)

const (
	skillBundleDir  = "skills/fakturownia"
	skillDocsIndex  = "docs/skills.md"
	generatedByLine = "> Auto-generated by `go run ./cmd/gen-skills`. Do not edit manually."
)

type SkillCommandRef struct {
	Noun string `json:"noun"`
	Verb string `json:"verb"`
}

type SkillAreaSpec struct {
	Key           string            `json:"key"`
	Name          string            `json:"name"`
	Title         string            `json:"title"`
	Description   string            `json:"description"`
	Category      string            `json:"category"`
	Prerequisite  string            `json:"prerequisite,omitempty"`
	RelatedSkills []string          `json:"related_skills,omitempty"`
	CommandRefs   []SkillCommandRef `json:"command_refs,omitempty"`
	ExampleRefs   []SkillCommandRef `json:"example_refs,omitempty"`
	CLIHelp       string            `json:"cli_help"`
	RequiresBins  []string          `json:"requires_bins,omitempty"`
	DiscoveryHint string            `json:"discovery_hint,omitempty"`
	WhenToUse     []string          `json:"when_to_use,omitempty"`
}

type SkillBundleSpec struct {
	Name          string          `json:"name"`
	Title         string          `json:"title"`
	Description   string          `json:"description"`
	CLIHelp       string          `json:"cli_help"`
	RequiresBins  []string        `json:"requires_bins,omitempty"`
	DiscoveryHint string          `json:"discovery_hint,omitempty"`
	Areas         []SkillAreaSpec `json:"areas"`
}

func SkillBundle() SkillBundleSpec {
	return SkillBundleSpec{
		Name:        "fakturownia",
		Title:       "fakturownia",
		Description: "Fakturownia CLI bundle: shared guidance, auth, accounts, departments, issuers, users, categories, clients, payments, bank accounts, products, price lists, invoices, recurrings, warehouses, warehouse actions, warehouse documents, webhooks, self-update, schema discovery, diagnostics, and generated invoice recipes for the `fakturownia` command. Use when an agent needs to work with Fakturownia through this CLI.",
		CLIHelp:     "fakturownia --help",
		RequiresBins: []string{
			"fakturownia",
		},
		DiscoveryHint: "Open the bundle-local skills index first, then read the shared skill, then the area skill that matches the task.",
		Areas: []SkillAreaSpec{
			{
				Key:         "shared",
				Name:        "fakturownia-shared",
				Title:       "Shared",
				Description: "Fakturownia CLI shared patterns: authentication prerequisites, global flags, output modes, `--fields` vs `--columns`, `--raw`, schema discovery, and binary maintenance. Use before any area-specific fakturownia task.",
				Category:    "core",
				CommandRefs: []SkillCommandRef{
					{Noun: "self", Verb: "update"},
				},
				ExampleRefs: []SkillCommandRef{
					{Noun: "auth", Verb: "login"},
					{Noun: "auth", Verb: "exchange"},
					{Noun: "account", Verb: "get"},
					{Noun: "department", Verb: "list"},
					{Noun: "issuer", Verb: "list"},
					{Noun: "webhook", Verb: "list"},
					{Noun: "category", Verb: "list"},
					{Noun: "schema", Verb: "list"},
					{Noun: "self", Verb: "update"},
					{Noun: "client", Verb: "list"},
					{Noun: "payment", Verb: "list"},
					{Noun: "bank-account", Verb: "list"},
					{Noun: "product", Verb: "list"},
					{Noun: "price-list", Verb: "list"},
					{Noun: "invoice", Verb: "list"},
					{Noun: "recurring", Verb: "list"},
					{Noun: "warehouse", Verb: "list"},
					{Noun: "warehouse-action", Verb: "list"},
					{Noun: "warehouse-document", Verb: "list"},
				},
				CLIHelp: "fakturownia --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Start here for global behavior, then use `fakturownia schema list --json` to discover supported command groups.",
				WhenToUse: []string{
					"The task is generally about the `fakturownia` CLI rather than one specific noun.",
					"You need auth setup, global flags, output behavior, or command discovery before calling API-area commands.",
					"You need to update the installed fakturownia binary from GitHub Releases.",
				},
			},
			{
				Key:          "auth",
				Name:         "fakturownia-auth",
				Title:        "Auth",
				Description:  "Fakturownia CLI auth: persist, inspect, and remove profiles and API tokens with `fakturownia auth ...`.",
				Category:     "core",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"accounts",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "auth", Verb: "login"},
					{Noun: "auth", Verb: "exchange"},
					{Noun: "auth", Verb: "status"},
					{Noun: "auth", Verb: "logout"},
				},
				CLIHelp: "fakturownia auth --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `auth login` before API calls, or `auth status --json` to inspect the resolved profile and token source.",
				WhenToUse: []string{
					"You need to save a profile, exchange login credentials for an API token, verify which profile is active, or clean up a persisted token.",
					"You need to explain or troubleshoot how env vars, profiles, keychain-backed credentials, and sanitized secret-handling resolve.",
				},
			},
			{
				Key:          "accounts",
				Name:         "fakturownia-accounts",
				Title:        "Accounts",
				Description:  "Fakturownia CLI accounts: create, inspect, delete, and unlink system accounts using the README-backed account contract, with sanitized structured output and optional profile persistence.",
				Category:     "core",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"auth",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "account", Verb: "create"},
					{Noun: "account", Verb: "get"},
					{Noun: "account", Verb: "delete"},
					{Noun: "account", Verb: "unlink"},
				},
				CLIHelp: "fakturownia account --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema account create --json` before building full account request objects, and prefer structured output unless you explicitly need `--raw` to inspect returned secrets.",
				WhenToUse: []string{
					"The task is about system-account creation, inspection, deletion, or unlinking partner-linked accounts.",
					"You need to work with the full top-level `account` request shape rather than the CLI's usual inner-object `--input` contract.",
				},
			},
			{
				Key:          "departments",
				Name:         "fakturownia-departments",
				Title:        "Departments",
				Description:  "Fakturownia CLI departments: list, fetch, create, update, delete, and upload department logos, with README-backed request and output discovery.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"users",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "department", Verb: "list"},
					{Noun: "department", Verb: "get"},
					{Noun: "department", Verb: "create"},
					{Noun: "department", Verb: "update"},
					{Noun: "department", Verb: "delete"},
					{Noun: "department", Verb: "set-logo"},
				},
				CLIHelp: "fakturownia department --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema department list --json` for output fields and `fakturownia schema department create --json` before building department payloads or uploading a logo.",
				WhenToUse: []string{
					"The task is about reading or mutating departments or uploading department logos.",
					"You need README-backed department fields such as `name`, `shortcut`, or `tax_no` before building payloads.",
				},
			},
			{
				Key:          "issuers",
				Name:         "fakturownia-issuers",
				Title:        "Issuers",
				Description:  "Fakturownia CLI issuers: list, fetch, create, update, and delete issuers with README-backed field and payload discovery.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"invoices",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "issuer", Verb: "list"},
					{Noun: "issuer", Verb: "get"},
					{Noun: "issuer", Verb: "create"},
					{Noun: "issuer", Verb: "update"},
					{Noun: "issuer", Verb: "delete"},
				},
				CLIHelp: "fakturownia issuer --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema issuer list --json` for output fields and `fakturownia schema issuer create --json` before building issuer payloads.",
				WhenToUse: []string{
					"The task is about reading or mutating invoice issuers.",
					"You need README-backed issuer fields such as `name` and `tax_no` before creating or updating an issuer.",
				},
			},
			{
				Key:          "users",
				Name:         "fakturownia-users",
				Title:        "Users",
				Description:  "Fakturownia CLI users: create or invite account users through the README-backed add-user endpoint and inspect the accepted user payload shape.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"departments",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "user", Verb: "create"},
				},
				CLIHelp: "fakturownia user --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema user create --json` before building invite or password-based user payloads, and pass `--integration-token` separately.",
				WhenToUse: []string{
					"The task is about adding or inviting a user to an account.",
					"You need the README-backed `user` payload shape, especially `invite`, `role`, and `department_ids[]`.",
				},
			},
			{
				Key:          "webhooks",
				Name:         "fakturownia-webhooks",
				Title:        "Webhooks",
				Description:  "Fakturownia CLI webhooks: list, fetch, create, update, and delete webhooks using conservative README-backed request and output discovery.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"clients",
					"invoices",
					"products",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "webhook", Verb: "list"},
					{Noun: "webhook", Verb: "get"},
					{Noun: "webhook", Verb: "create"},
					{Noun: "webhook", Verb: "update"},
					{Noun: "webhook", Verb: "delete"},
				},
				CLIHelp: "fakturownia webhook --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema webhook list --json` for output fields and `fakturownia schema webhook create --json` before building full top-level webhook request objects.",
				WhenToUse: []string{
					"The task is about reading or mutating webhooks.",
					"You need the conservative webhook `kind`, `url`, `api_token`, and `active` request contract without inventing undocumented wrapper keys.",
				},
			},
			{
				Key:          "categories",
				Name:         "fakturownia-categories",
				Title:        "Categories",
				Description:  "Fakturownia CLI categories: list, fetch, create, update, and delete categories, and inspect README-backed category fields and request schemas.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "category", Verb: "list"},
					{Noun: "category", Verb: "get"},
					{Noun: "category", Verb: "create"},
					{Noun: "category", Verb: "update"},
					{Noun: "category", Verb: "delete"},
				},
				CLIHelp: "fakturownia category --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema category list --json` for output fields and `fakturownia schema category create --json` or `category update --json` for request-body discovery.",
				WhenToUse: []string{
					"The task is about reading or mutating categories.",
					"You need to inspect README-backed category fields before creating or updating category payloads.",
				},
			},
			{
				Key:          "clients",
				Name:         "fakturownia-clients",
				Title:        "Clients",
				Description:  "Fakturownia CLI clients: list, fetch, create, update, and delete clients, and inspect README-backed client fields and request schemas.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "client", Verb: "list"},
					{Noun: "client", Verb: "get"},
					{Noun: "client", Verb: "create"},
					{Noun: "client", Verb: "update"},
					{Noun: "client", Verb: "delete"},
				},
				CLIHelp: "fakturownia client --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema client list --json` for output fields and `fakturownia schema client create --json` or `client update --json` for request-body discovery before building selectors or payloads.",
				WhenToUse: []string{
					"The task is about reading or mutating clients, including lookup by external ID.",
					"You need to build a client payload from README-backed field definitions and inspect `request_body_schema` before create or update calls.",
				},
			},
			{
				Key:          "payments",
				Name:         "fakturownia-payments",
				Title:        "Payments",
				Description:  "Fakturownia CLI payments: list, fetch, create, update, and delete banking payments, including the README-backed `include=invoices` list mode and request-body discovery.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"invoices",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "payment", Verb: "list"},
					{Noun: "payment", Verb: "get"},
					{Noun: "payment", Verb: "create"},
					{Noun: "payment", Verb: "update"},
					{Noun: "payment", Verb: "delete"},
				},
				CLIHelp: "fakturownia payment --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema payment list --json` for output fields and `fakturownia schema payment create --json` or `payment update --json` for request-body discovery.",
				WhenToUse: []string{
					"The task is about reading or mutating banking payments.",
					"You need the README-backed `--include invoices` list mode or to build payment payloads with `invoice_id` or `invoice_ids`.",
				},
			},
			{
				Key:          "bank-accounts",
				Name:         "fakturownia-bank-accounts",
				Title:        "Bank Accounts",
				Description:  "Fakturownia CLI bank accounts: list, fetch, create, update, and delete bank accounts, and inspect the bank-account addendum fields that also affect invoice payloads.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"invoices",
					"departments",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "bank-account", Verb: "list"},
					{Noun: "bank-account", Verb: "get"},
					{Noun: "bank-account", Verb: "create"},
					{Noun: "bank-account", Verb: "update"},
					{Noun: "bank-account", Verb: "delete"},
				},
				CLIHelp: "fakturownia bank-account --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema bank-account list --json` for output discovery and `fakturownia schema bank-account create --json` before building `bank_account` payloads with `name`, `bank_account_number`, and `bank_currency` or invoice bank-account fields.",
				WhenToUse: []string{
					"The task is about reading or mutating bank accounts exposed by API_RACHUNKI_BANKOWE.md.",
					"You need invoice bank-account fields such as `bank_account_id`, `buyer_mass_payment_code`, or embedded `bank_accounts[]` and want the matching schema guidance.",
				},
			},
			{
				Key:          "products",
				Name:         "fakturownia-products",
				Title:        "Products",
				Description:  "Fakturownia CLI products: list, fetch, create, and update products, including warehouse-aware reads and README-backed request schemas.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "product", Verb: "list"},
					{Noun: "product", Verb: "get"},
					{Noun: "product", Verb: "create"},
					{Noun: "product", Verb: "update"},
				},
				CLIHelp: "fakturownia product --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema product list --json` for output fields and `fakturownia schema product create --json` or `product update --json` for request-body discovery before building selectors or payloads.",
				WhenToUse: []string{
					"The task is about reading or mutating products, including warehouse-aware stock views.",
					"You need to inspect README-backed product fields or package-product payload requirements before create or update calls.",
				},
			},
			{
				Key:          "price-lists",
				Name:         "fakturownia-price-lists",
				Title:        "Price Lists",
				Description:  "Fakturownia CLI price lists: list, fetch, create, update, and delete price lists, including upstream-shaped position payloads and schema-backed discovery.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"products",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "price-list", Verb: "list"},
					{Noun: "price-list", Verb: "get"},
					{Noun: "price-list", Verb: "create"},
					{Noun: "price-list", Verb: "update"},
					{Noun: "price-list", Verb: "delete"},
				},
				CLIHelp: "fakturownia price-list --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema price-list list --json` for output fields and `fakturownia schema price-list create --json` for the upstream-shaped request contract, especially `price_list_positions_attributes`.",
				WhenToUse: []string{
					"The task is about reading or mutating price lists and their position entries.",
					"You need to inspect the verified `price-list get` output shape or build upstream-shaped `price_list_positions_attributes` payloads before create or update calls.",
				},
			},
			{
				Key:          "invoices",
				Name:         "fakturownia-invoices",
				Title:        "Invoices",
				Description:  "Fakturownia CLI invoices: list, fetch, create, update, delete, email, cancel, send to KSeF through the API-native `gov` flow, download invoice attachments, and discover invoice fields and payloads through schema output.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"products",
					"bank-accounts",
					"price-lists",
					"recurrings",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "invoice", Verb: "list"},
					{Noun: "invoice", Verb: "get"},
					{Noun: "invoice", Verb: "create"},
					{Noun: "invoice", Verb: "update"},
					{Noun: "invoice", Verb: "delete"},
					{Noun: "invoice", Verb: "send-email"},
					{Noun: "invoice", Verb: "send-gov"},
					{Noun: "invoice", Verb: "change-status"},
					{Noun: "invoice", Verb: "cancel"},
					{Noun: "invoice", Verb: "public-link"},
					{Noun: "invoice", Verb: "add-attachment"},
					{Noun: "invoice", Verb: "download-attachment"},
					{Noun: "invoice", Verb: "download-attachments"},
					{Noun: "invoice", Verb: "fiscal-print"},
					{Noun: "invoice", Verb: "download"},
				},
				CLIHelp: "fakturownia invoice --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema invoice list --json` or `fakturownia schema invoice get --json` before building `--fields` selectors, KSeF `gov_*` projections, or nested invoice payloads.",
				WhenToUse: []string{
					"The task is about reading or mutating invoices, sending invoice emails, sending invoices to KSeF through the API-native `gov` flow, printing fiscally, or attaching files.",
					"You need to discover invoice output fields such as `number`, `status`, `token`, `gov_status`, or nested paths like `positions[].name`.",
					"You need to inspect `request_body_schema` before constructing `invoice create` or `invoice update` payloads.",
				},
			},
			{
				Key:          "recurrings",
				Name:         "fakturownia-recurrings",
				Title:        "Recurrings",
				Description:  "Fakturownia CLI recurrings: list, create, and update recurring invoice definitions with README-backed request and output discovery.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"invoices",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "recurring", Verb: "list"},
					{Noun: "recurring", Verb: "create"},
					{Noun: "recurring", Verb: "update"},
				},
				CLIHelp: "fakturownia recurring --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema recurring list --json` and `fakturownia schema recurring create --json` before building selectors or payloads.",
				WhenToUse: []string{
					"The task is about recurring invoice definitions rather than concrete invoice documents.",
					"You need README-backed `request_body_schema` guidance for recurring creation or next-date updates.",
				},
			},
			{
				Key:          "warehouses",
				Name:         "fakturownia-warehouses",
				Title:        "Warehouses",
				Description:  "Fakturownia CLI warehouses: list, fetch, create, update, and delete warehouses, and inspect README-backed warehouse fields and request schemas.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"warehouse-actions",
					"warehouse-documents",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "warehouse", Verb: "list"},
					{Noun: "warehouse", Verb: "get"},
					{Noun: "warehouse", Verb: "create"},
					{Noun: "warehouse", Verb: "update"},
					{Noun: "warehouse", Verb: "delete"},
				},
				CLIHelp: "fakturownia warehouse --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema warehouse list --json` for output discovery and `fakturownia schema warehouse create --json` before building warehouse payloads.",
				WhenToUse: []string{
					"The task is about reading or mutating warehouse definitions.",
					"You need README-backed warehouse fields before creating or updating a warehouse payload.",
				},
			},
			{
				Key:          "warehouse-actions",
				Name:         "fakturownia-warehouse-actions",
				Title:        "Warehouse Actions",
				Description:  "Fakturownia CLI warehouse actions: list warehouse actions with explicit README-backed filters and inspect conservative action fields through schema output.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"warehouses",
					"warehouse-documents",
					"products",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "warehouse-action", Verb: "list"},
				},
				CLIHelp: "fakturownia warehouse-action --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema warehouse-action list --json` to inspect output fields, then narrow queries with the explicit warehouse-action filter flags.",
				WhenToUse: []string{
					"The task is about reading warehouse stock movements or filtering actions by warehouse, product, document, kind, or date range.",
					"You need conservative README-backed warehouse action fields without mutating warehouse state.",
				},
			},
			{
				Key:          "warehouse-documents",
				Name:         "fakturownia-warehouse-documents",
				Title:        "Warehouse Documents",
				Description:  "Fakturownia CLI warehouse documents: list, fetch, create, update, and delete warehouse documents, including kind selection and invoice linking through payload fields.",
				Category:     "api-area",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"products",
					"invoices",
					"warehouses",
					"warehouse-actions",
					"schema",
					"doctor",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "warehouse-document", Verb: "list"},
					{Noun: "warehouse-document", Verb: "get"},
					{Noun: "warehouse-document", Verb: "create"},
					{Noun: "warehouse-document", Verb: "update"},
					{Noun: "warehouse-document", Verb: "delete"},
				},
				CLIHelp: "fakturownia warehouse-document --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use `fakturownia schema warehouse-document list --json` for output discovery and `fakturownia schema warehouse-document create --json` before building `warehouse_actions[]` or `invoice_ids[]` payloads.",
				WhenToUse: []string{
					"The task is about warehouse transfers, receipts, releases, or related warehouse-document maintenance.",
					"You need to choose warehouse document kinds through the payload, or link invoices using `invoice_ids[]` during updates.",
				},
			},
			{
				Key:          "schema",
				Name:         "fakturownia-schema",
				Title:        "Schema",
				Description:  "Fakturownia CLI schema discovery: inspect supported commands, flags, examples, exit codes, and output schemas with `fakturownia schema ...`.",
				Category:     "core",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"accounts",
					"departments",
					"issuers",
					"users",
					"products",
					"price-lists",
					"invoices",
					"recurrings",
					"webhooks",
					"warehouses",
					"warehouse-actions",
					"warehouse-documents",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "schema", Verb: "list"},
					{Noun: "schema", Verb: "<noun> <verb>"},
				},
				CLIHelp: "fakturownia schema --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use schema output to inspect a command before calling it; for invoices, read `output.known_fields` and `path_syntax`.",
				WhenToUse: []string{
					"You need machine-readable command discovery instead of scraping `--help` text.",
					"You need to inspect flags, env vars, examples, exit codes, output catalogs, or request-body schemas before executing a command.",
				},
			},
			{
				Key:          "doctor",
				Name:         "fakturownia-doctor",
				Title:        "Doctor",
				Description:  "Fakturownia CLI diagnostics: validate config resolution, keychain access, reachability, authenticated API access, and release integrity with `fakturownia doctor run`.",
				Category:     "core",
				Prerequisite: "shared",
				RelatedSkills: []string{
					"shared",
					"auth",
				},
				CommandRefs: []SkillCommandRef{
					{Noun: "doctor", Verb: "run"},
				},
				CLIHelp: "fakturownia doctor --help",
				RequiresBins: []string{
					"fakturownia",
				},
				DiscoveryHint: "Use doctor when auth or API behavior is unclear and you need deterministic remediation checks instead of guessing.",
				WhenToUse: []string{
					"You need a deterministic health check for config, auth, network, or release integrity.",
					"You are debugging a failed API call and want the CLI to verify the local environment first.",
				},
			},
		},
	}
}

func skillAreaByKey(bundle SkillBundleSpec, key string) (SkillAreaSpec, bool) {
	for _, area := range bundle.Areas {
		if area.Key == key {
			return area, true
		}
	}
	return SkillAreaSpec{}, false
}

func commandSpecForSkillRef(ref SkillCommandRef) (CommandSpec, error) {
	spec, ok := FindCommand(ref.Noun, ref.Verb)
	if !ok {
		return CommandSpec{}, fmt.Errorf("unknown skill command reference %s %s", ref.Noun, ref.Verb)
	}
	return spec, nil
}

func skillCommandAssignments(bundle SkillBundleSpec) (map[SkillCommandRef]string, error) {
	assignments := make(map[SkillCommandRef]string)
	for _, area := range bundle.Areas {
		for _, ref := range area.CommandRefs {
			if _, err := commandSpecForSkillRef(ref); err != nil {
				return nil, err
			}
			if owner, ok := assignments[ref]; ok {
				return nil, fmt.Errorf("skill command reference %s %s assigned to both %s and %s", ref.Noun, ref.Verb, owner, area.Key)
			}
			assignments[ref] = area.Key
		}
	}
	return assignments, nil
}

func commandsForSkillArea(area SkillAreaSpec) ([]CommandSpec, error) {
	specs := make([]CommandSpec, 0, len(area.CommandRefs))
	for _, ref := range area.CommandRefs {
		spec, err := commandSpecForSkillRef(ref)
		if err != nil {
			return nil, err
		}
		specs = append(specs, spec)
	}
	return specs, nil
}

func exampleCommandsForSkillArea(area SkillAreaSpec) ([]CommandSpec, error) {
	refs := area.CommandRefs
	if len(area.ExampleRefs) > 0 {
		refs = area.ExampleRefs
	}
	seen := make(map[SkillCommandRef]struct{}, len(refs))
	specs := make([]CommandSpec, 0, len(refs))
	for _, ref := range refs {
		if _, ok := seen[ref]; ok {
			continue
		}
		seen[ref] = struct{}{}
		spec, err := commandSpecForSkillRef(ref)
		if err != nil {
			return nil, err
		}
		specs = append(specs, spec)
	}
	return specs, nil
}

func envVarsForCommands(specs []CommandSpec) []EnvVarSpec {
	seen := map[string]struct{}{}
	out := make([]EnvVarSpec, 0)
	for _, spec := range specs {
		for _, env := range spec.EnvVars {
			if _, ok := seen[env.Name]; ok {
				continue
			}
			seen[env.Name] = struct{}{}
			out = append(out, env)
		}
	}
	return out
}

func flagsForCommands(specs []CommandSpec) []FlagSpec {
	seen := map[string]struct{}{}
	out := make([]FlagSpec, 0)
	for _, spec := range specs {
		for _, flag := range spec.LocalFlags {
			if _, ok := seen[flag.Name]; ok {
				continue
			}
			seen[flag.Name] = struct{}{}
			out = append(out, flag)
		}
	}
	return out
}

func examplesForCommands(specs []CommandSpec) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0)
	for _, spec := range specs {
		for _, example := range spec.Examples {
			if _, ok := seen[example]; ok {
				continue
			}
			seen[example] = struct{}{}
			out = append(out, example)
		}
	}
	return out
}

func bundleRootSkillPath() string {
	return filepath.ToSlash(filepath.Join("skills", "fakturownia", "SKILL.md"))
}

func bundleIndexPath() string {
	return filepath.ToSlash(filepath.Join("skills", "fakturownia", "references", "skills-index.md"))
}

func skillAreaPath(area SkillAreaSpec) string {
	return filepath.ToSlash(filepath.Join("skills", "fakturownia", "subskills", area.Key, "SKILL.md"))
}

func docsSkillsPath() string {
	return skillDocsIndex
}

func sharedSkillArea(bundle SkillBundleSpec) SkillAreaSpec {
	area, ok := skillAreaByKey(bundle, "shared")
	if !ok {
		panic("missing shared skill area")
	}
	return area
}

func skillAreaCommandTitle(spec CommandSpec) string {
	if spec.Verb == "<noun> <verb>" {
		return "fakturownia " + spec.Noun + " <noun> <verb>"
	}
	return "fakturownia " + spec.Noun + " " + spec.Verb
}

func relatedAreas(bundle SkillBundleSpec, area SkillAreaSpec) []SkillAreaSpec {
	out := make([]SkillAreaSpec, 0, len(area.RelatedSkills))
	for _, key := range area.RelatedSkills {
		resolved, ok := skillAreaByKey(bundle, key)
		if ok {
			out = append(out, resolved)
		}
	}
	return out
}

func skillsByCategory(bundle SkillBundleSpec, category string) []SkillAreaSpec {
	out := make([]SkillAreaSpec, 0)
	for _, area := range bundle.Areas {
		if area.Category == category {
			out = append(out, area)
		}
	}
	return out
}

func validateSkillBundle(bundle SkillBundleSpec) error {
	if strings.TrimSpace(bundle.Name) == "" {
		return fmt.Errorf("skill bundle name is required")
	}
	if _, err := skillCommandAssignments(bundle); err != nil {
		return err
	}
	expected := make([]SkillCommandRef, 0, len(Registry()))
	for _, command := range Registry() {
		expected = append(expected, SkillCommandRef{Noun: command.Noun, Verb: command.Verb})
	}
	assignments, err := skillCommandAssignments(bundle)
	if err != nil {
		return err
	}
	for _, ref := range expected {
		if _, ok := assignments[ref]; !ok {
			return fmt.Errorf("command %s %s is not assigned to any skill area", ref.Noun, ref.Verb)
		}
	}
	for _, area := range bundle.Areas {
		if strings.TrimSpace(area.Name) == "" {
			return fmt.Errorf("skill area %s is missing a name", area.Key)
		}
		if strings.TrimSpace(area.Description) == "" {
			return fmt.Errorf("skill area %s is missing a description", area.Key)
		}
		if area.Prerequisite != "" {
			if _, ok := skillAreaByKey(bundle, area.Prerequisite); !ok {
				return fmt.Errorf("skill area %s has unknown prerequisite %s", area.Key, area.Prerequisite)
			}
		}
		for _, related := range area.RelatedSkills {
			if _, ok := skillAreaByKey(bundle, related); !ok {
				return fmt.Errorf("skill area %s has unknown related skill %s", area.Key, related)
			}
		}
	}
	return nil
}
